import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "learning next",
    template: "%s | title",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <p>header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "grey", padding: "1rem" }}>
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
